name: Deploy Backend to AWS EB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Backend Deployment Package
        run: |
          cd backend
          zip -r ../backend-deploy.zip . -x "node_modules/*" "tests/*" ".env*" "testing/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: AHARA_BACKEND # REPLACE with your actual EB App Name
          environment_name: AHARABACKEND-env # REPLACE with your actual EB Env Name
          version_label: backend-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: backend-deploy.zip
